/// Flutter icons PreviewIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PreviewIcons
///      fonts:
///       - asset: fonts/PreviewIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PreviewIcons {
  PreviewIcons._();

  static const _kFontFam = 'PreviewIcons';
  static const _kFontPkg = 'preview';

  static const IconData lightning_bolt = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
